### ISSUE TITLE
Vignettes are not built

### ISSUE THREAD

**Issue by hsonne** [KWB-R/kwb.pkgbuild#12]
What do I do wrong? The folowing does not install vignettes on my computer:

```
devtools::install_github("KWB-R/kwb.pkgbuild", build_vignettes = TRUE)
```

**Comment by mrustl** [comment]
See here: https://github.com/r-lib/devtools/issues/1578

**Comment by hsonne** [comment]
You are my hero. Unfortunately I get this:
```
E  creating vignettes (3s)
   pandoc.exe: Could not fetch https://img.shields.io/badge/License-MIT-yellow.svg
   TlsExceptionHostPort (HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,HandshakeFailure)])")) "img.shields.io" 443
   Fehler: Verarbeitung der Vignette 'tutorial.Rmd' mit folgender Diagnose fehlgeschlagen:
   pandoc document conversion failed with error 67
   Ausführung angehalten
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
```

**Comment by mrustl** [comment]
Check your PANDOC version: 
` rmarkdown::pandoc_version()`

Versions < 2.0 seem to have some problems with "https:" 

It worked with [pandoc-2.2.1](https://pandoc.org/releases.html#pandoc-2.2.1-10-may-2018) on my computer. 

Now I downloded the preview RStudio (https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.2.1163.zip) which ships with [pandoc 2.5](https://pandoc.org/releases.html#pandoc-2.5-27-november-2018) and that also works for me! 

If you want to test the new RStudio you can do that as it is portable: 
https://support.rstudio.com/hc/en-us/articles/200534467-Creating-a-Portable-Version-of-RStudio-for-a-USB-Drive

**Comment by hsonne** [comment]
I am so oldschool!
```
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
```
