### ISSUE TITLE
How to provide students access to private github packages

### ISSUE THREAD

**Issue by mstapf1** [KWB-R/kwb.pkgbuild#25]

**Comment by hsonne** [comment]
@mrustl I have written something for sema.berlin (in German) that we may use
https://github.com/KWB-R/sema.berlin/blob/dev/vignettes/get_started.Rmd

**Comment by mrustl** [comment]
New dependency kwb.orcid was missing

**Comment by mrustl** [comment]
Closed by https://github.com/KWB-R/kwb.pkgbuild/commit/ab52d827ae013898c6aae66b3fceb3bf4f685e60
