### ISSUE TITLE
README .Rmd and .md not completely the same!

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.pkgbuild#6]
The README.Rmd (used to the docu website contained no links to the site itself and the package name). With your recreation of .md from .Rmd this separation is now not the case anymore.

Compare here: https://github.com/KWB-R/kwb.pkgbuild/commit/0844c3afce5c12e6cfb288728c4ae89d47b16423 

README is created with R function. See here: https://github.com/KWB-R/kwb.pkgbuild/blob/master/R/use_readme.R

**Comment by hsonne** [comment]
I do not get the point. What is the problem? My idea was that for each package a README.Rmd is created that already contains 

* Installation section
* Documentation section with links to the documentation. 

README.md must then (manually) be created from the README.Rmd

**Comment by mrustl** [comment]
pkgdown has a priority for building the index.html: 
http://pkgdown.r-lib.org/articles/pkgdown.html#home-page 

As README.md (e.g. https://github.com/KWB-R/kwb.qmra/README.md) should be not the same as for the README.Rmd (https://github.com/KWB-R/kwb.qmra/README.Rmd) used for generating the "index.html" for the documentation site. 

We could also rename the "README.Rmd" into "index.Rmd" if this makes things clearer.
