### ISSUE TITLE
Move away from Travis (-> GitHub Actions )

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.pkgbuild#78]
"Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting."

Also mentioned here:

https://yoursunny.com/t/2020/TravisCI-credits/

![Screenshot_2020-11-18-17-42-48-455_com android chrome](https://user-images.githubusercontent.com/11964451/99560090-c11afe80-29c5-11eb-8fa0-a98a017822d7.jpg)

**Comment by mrustl** [comment]
@hsonne on which machines should we test by default our public R package. Currently I only use "windows with latest R" (and mac-os (for pkgdown as that for some reason has failed to deploy on gh-pages in the past)

Should we do: 
- macos (r-latest)
- windows (r-old, r-latest, r-dev) 
- linux (r-latest)

**Comment by hsonne** [comment]
Your above list looks good to me.
